[tool.poetry]
name = "projeto-teste"
version = "0.1.0"
description = "Projeto teste para ambiente profissional"
authors = ["Lucas Seixas Dias <lseixasd@gmail.com>"]
readme = "README.md"
packages = [{ include = "projeto_teste", from = "src" }]

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.group.dev.dependencies]
black = "^26.1.0"
ruff = "^0.15.1"
pytest = "^8.0"
pre-commit = "^3.7.0"

[tool.black]
line-length = 88
target-version = ["py312"]

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]

# E → erros estilo pycodestyle
# F → erros lógicos (pyflakes)
# I → ordenação de imports
# UP → melhorias modernas de sintaxe

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
